services:
  - type: web
    name: tofbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    plan: free
    envVars:
      - key: WEB_CONCURRENCY
        value: "1"
